name: Build Status

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron:  '0 15 * * 1' # mondays at 15:00 UTC (12:00 UTC-3)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install NPM
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install VS Code Extension
        run: |
          npm install -g  @vscode/vsce
          npx @vscode/vsce --version

      - name: Build Colang Extension
        run: |
          npm install
          vsce package
        working-directory: ./colang-lang
